monitor.bluez.rules = [
  {
    matches = [ { device.name = "bluez_card.2C_CF_67_58_3F_4A" } ]
    actions.update-props = {
      # Restrict to Opus only — aptX HD causes clock drift skips on the Pi 5
      bluez5.codecs = [ opus_05 sbc_xq sbc ]
    }
  }
]
