[aliases]
  "hello-world" = "docker.io/library/hello-world"
  "vault" = "docker.io/hashicorp/vault"
  "netdata" = "docker.io/netdata/netdata"
  "glances" = "docker.io/nicolargo/glances"
  "ubuntu" = "docker.io/library/ubuntu"
  "golang" = "docker.io/library/golang"
  "alpine" = "docker.io/alpine"
  "alpine/git" = "docker.io/alpine/git"
  "quintush/helm-unittest" = "docker.io/quintush/helm-unittest"
