[tools]
node = '24'
bun = '1'
python = '3.14'
zig = 'latest'
go = '1.26'
meson = 'latest'
chezmoi = 'latest'
cilium-cli = 'latest'
cilium-hubble = 'latest'
'aqua:hashicorp/packer' = 'latest'
#'aqua:jesseduffield/lazygit' = 'latest'
'aqua:kubernetes-sigs/kustomize' = 'latest'
'aqua:bitnami-labs/sealed-secrets' = 'latest'
'aqua:yannh/kubeconform' = 'latest'
'aqua:stackrox/kube-linter' = 'latest'
'aqua:robscott/kube-capacity' = 'latest'
'aqua:derailed/k9s' = 'latest'
'aqua:kubernetes-sigs/kind' = 'latest'
'aqua:jdx/hk' = 'latest'
'aqua:mrjosh/helm-ls' = 'latest'
'aqua:norwoodj/helm-docs' = 'latest'
'aqua:tmccombs/hcl2json' = 'latest'
'aqua:git-lfs/git-lfs' = 'latest'
'aqua:homeport/dyff' = 'latest'
'aqua:nektos/act' = 'latest'
'aqua:projectcalico/calico/calicoctl' = 'latest'
'aqua:cloudflare/cfssl/cfssl' = 'latest'
'aqua:bridgecrewio/checkov' = 'latest'
'aqua:FiloSottile/mkcert' = 'latest'
'aqua:mozilla/sccache' = 'latest'
'aqua:helm/helm' = '3.20.0'
'aqua:gohugoio/hugo' = 'latest'
'aqua:vmware-tanzu/velero' = 'latest'
'aqua:mikefarah/yq' = 'latest'
'aqua:argoproj/argo-cd' = '3.3.2'
'aqua:kyverno/kyverno' = '1.17.1'
'aqua:astral-sh/uv' = 'latest'
'aqua:jedisct1/minisign' = 'latest'
'aqua:istio/istio/istioctl' = '1.27'
'aqua:derailed/popeye' = 'latest'
'aqua:go-task/task' = 'latest'
'aqua:carvel-dev/vendir' = 'latest'
'aqua:hashicorp/terraform' = '1.14.6'
'aqua:hashicorp/terraform-ls' = 'latest'
'aqua:terraform-linters/tflint' = 'latest'
'aqua:sxyazi/yazi' = 'latest'
'aqua:ducaale/xh' = 'latest'
'aqua:ajeetdsouza/zoxide' = 'latest'
'aqua:starship/starship' = 'latest'
'aqua:ast-grep/ast-grep' = 'latest'
'aqua:google/yamlfmt' = 'latest'
'aqua:sharkdp/hyperfine' = 'latest'
'aqua:JohnnyMorganz/StyLua' = 'latest'
'aqua:dandavison/delta' = 'latest'
gradle = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

