max-gamma = 150

profile {
    time = 6:30
    identity = true
}

profile {
    time = 17:30
    temperature = 5400
    gamma = 0.95
}

profile {
    time = 18:00
    temperature = 4900
    gamma = 0.9
}

profile {
    time = 19:00
    temperature = 4400
    gamma = 0.8
}
